### ISSUE TITLE
Too many threads

### ISSUE THREAD

**Issue by du4** [rossmann-engineering/EasyModbusTCP.Java#8]
Hello. 
Every client connection to Easy Modbus Server a new thread is created, but at the disconnect it didn't kills. If we have 1k connect-disconnect we have a 1k threads.

**Comment by vilelam** [comment]
@du4 were you able to find a solution for that? my server is consuming all the machine CPU after some received calls...

**Comment by du4** [comment]
Hi, Vilelam. I'm started to use other lib => jlibmodbus

**Comment by ThriftyNick** [comment]
Yes, I'm experiencing the same issue.  I have to restart the server periodically with a cron job to free the threads.

**Comment by C4J** [comment]
Did this ever get resolved ?

**Comment by rossmann-engineering** [comment]
Should be fixed now.
